version: "3"

services:
  nginx:
    container_name: nginx
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/letsencrypt/vhost.d:/etc/nginx/vhost.d
      - ./nginx/letsencrypt/certs:/etc/nginx/certs:ro
      - ./nginx/static:/usr/share/nginx/html
    environment:
      VIRTUAL_HOST: jonasleonhard.de
      LETSENCRYPT_HOST: jonasleonhard.de
  
  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx/letsencrypt/vhost.d:/etc/nginx/vhost.d
      - ./nginx/letsencrypt/certs:/etc/nginx/certs:rw
      - ./nginx/static:/usr/share/nginx/html
    environment:
      - NGINX_PROXY_CONTAINER=nginx

  backend_express:
    build: ./backend_express
    image: backend_express:prod
    container_name: backend_express
    environment:
      VIRTUAL_HOST: api.jonasleonhard.de
      LETSENCRYPT_HOST: jonasleonhard.de
    expose:
      - 3000