version: "3.3"

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/letsencrypt/vhost.d:/etc/nginx/vhost.d
      - ./nginx/letsencrypt/certs:/etc/nginx/certs:ro
      - ./nginx/letsencrypt/dhparam:/etc/nginx/dhparam
      - ./nginx/static:/usr/share/nginx/html

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx/letsencrypt/vhost.d:/etc/nginx/vhost.d
      - ./nginx/letsencrypt/certs:/etc/nginx/certs:rw
      - ./nginx/letsencrypt/acme/:/etc/acme.sh
      - ./nginx/letsencrypt/dhparam:/etc/nginx/dhparam
      - ./nginx/static:/usr/share/nginx/html
    environment:
      - NGINX_PROXY_CONTAINER=nginx

  backend_express:
    build: ./backend_express
    image: backend_express:prod
    container_name: backend_express
    environment:
      - VIRTUAL_HOST=jonasleonhard.de
      - LETSENCRYPT_HOST=jonasleonhard.de
      - VIRTUAL_PORT=3000
    expose:
      - "3000"

networks:
  default:
    external:
      name: nginx-proxy