version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx.html:/usr/share/nginx.html
    ports:
      - 80:80
      - 443:443
    environment:
      - DOCKERHOST=127.0.0.1
  fullstack_express_angular:
    build: ./fullstack_express_angular
    container_name: fullstack_express_angular
    ports:
      - 3200:3200

