version: '3'
services:
  backend_express:
    build: ./backend_express
    image: backend_express:prod
    ports:
      - 3000:3000

  frontend_angular_nginx_server:
    build: ./frontend_angular
    image: frontend_angular_nginx_server:prod
    ports: 
      - 4200:4200

