version: "3"
services:
  frontend:
    build: ./frontend
    image: frontend
    container_name: frontend
    volumes:
      - ./frontend/:/src
      - /src/node_modules
    environment:
      NEXT_PUBLIC_CMS_URL: ${NEXT_PUBLIC_CMS_URL:-http://localhost:1337}
    ports:
      - 127.0.0.1:3000:3000
