version: '3'
services:
  frontend:
    build: ./frontend
    image: frontend
    container_name: frontend
    volumes:
      - ./frontend/:/src
      - /src/node_modules
    environment:
      NEXT_PUBLIC_SERVERSIDE_APOLLO_CMS_URL: ${NEXT_PUBLIC_SERVERSIDE_APOLLO_CMS_URL:-http://strapi:1337}
      NEXT_PUBLIC_CLIENT_APOLLO_CMS_URL: ${NEXT_PUBLIC_CLIENT_APOLLO_CMS_URL:-http://localhost:1337}
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      - strapi

  strapi:
    build: ./backend
    image: backend
    container_name: backend
    ports:
      - 127.0.0.1:1337:1337
    volumes:
      - ./backend/:/opt/app
      - /opt/app/node_modules
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT:-postgres}
      DATABASE_NAME: ${DATABASE_NAME:-strapi}
      DATABASE_HOST: ${DATABASE_HOST:-postgres}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-postgres}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
    depends_on: 
      - postgres

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
    volumes:
      - postgres-strapidb:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d/
    ports:
      - 127.0.0.1:15432:5432
      
volumes:
  postgres-strapidb:
      driver: local