label: Settings
icon: settings
columns:
  - width: 3/3
    fields:
      cover:
        extends: fields/image
        label: Teaser Image
        help: The Image shown in teaser cards linking to this page
        required: false
      excerpt:
        label: Teaser Excerpt
        help: The excerpt is used in the teaser
        type: text
        maxlength: 200
      created:
        type: date
        time: true
        default: now
        width: 1/2
      tags:
        label: Tags
        type: tags
        width: 1/2
      related:
        label: Related pages
        type: pages
        query: page.siblings(false).listed
        max: 3
        help: In addition to relations through tags, this field can connect pages with a higher priority.
