title: File

accept:
  extension: svg, webp
  type: image

create:
  width: 800
  height: 600
  crop: true

fields:
  caption:
    label: Caption
    type: writer
    width: 1/2
    inline: true
  copyright:
    width: 1/2
    type: text
  alt:
    label: Alternative Text
    help: Used for alt attribute on images
    type: text
    width: 1/2
