name: Deployment CI&CD

on:
  push:
    branches: ["master"]

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Setup (workdir + update repo)
            nvm current 

            cd ~/vps
            git pull origin master
            git pull origin live
            git push

            # Backend (build)
            cd ~/vps/backend
            composer install

            # Frontend (build) 
            cd ~/vps/frontend
            yarn
            yarn build

            # Deploy (Restart with pm2)
            make pm2-restart
