name: Deployment CI&CD

on:
  push:
    branches: ["master"]

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            bash /var/www/html/vps/.github/workflows/deploy.bash
