title: Site

tabs:
  content:
    icon: dashboard
    columns:
      - width: 1/2
        sections:
          singles:
            type: pages
            create: false
            sortable: false
            sortBy: "title desc"
            empty: Please contact admin
            template:
              - error
              - admin-panel
              - home
          pages: sections/pages
      - width: 1
        sections:
          articlesPage:
            type: pages
            create: false
            sortable: false
            empty: Please contact admin
            template:
              - articles
          articles: sections/articles

  globals: sections/globals

  media:
    icon: folder
    label: Media
    sections:
      mediaPage:
        type: pages
        create: false
        sortable: false
        empty: Please contact admin
        template:
          - media
      media: sections/media

  seo:
    label: Default SEO
    extends: seo
