title: Site

tabs:
  content:
    icon: dashboard
    columns:
      - width: 1
        sections:
          Singles:
            type: pages
            create: false
            sortable: false
            sortBy: "title desc"
            empty: Please contact admin
            template:
              - error
              - admin-panel
              - home
              - blog
              - impressum
              - contact
              - about
              - projects
          pages: sections/pages

  globals: sections/globals

  media:
    icon: folder
    label: Media
    sections:
      mediaPage:
        type: pages
        create: false
        sortable: false
        empty: Please contact admin
        template:
          - media
      media: sections/media

  seo:
    label: Default SEO
    extends: seo
