title: Site

tabs:
  content:
    icon: dashboard
    columns:
      - width: 1
        sections:
          Singles:
            type: pages
            create: false
            sortable: false
            sortBy: "title desc"
            empty: Please contact admin
            template:
              - about
              - admin-panel
              - blog
              - contact
              - error
              - home
              - impressum
              - media
              - projects
              - search
          pages: sections/pages

  globals: sections/globals

  seo:
    label: Default SEO
    extends: seo
