title: Site
icon: 📖

columns:
  - width: 3/3
    sections:
      listed:
        type: pages
        create: default
        status: listed
        label: Listed

      unlisted:
        type: pages
        create: default
        status: unlisted
        label: Unlisted

      draft:
        type: pages
        create: default
        status: draft
        label: Draft
